plugins {
   id 'java-library'
}

group = 'org.writer'
version = '1.0-SNAPSHOT'

java {
   sourceCompatibility = JavaVersion.VERSION_17
   targetCompatibility = JavaVersion.VERSION_17
}

repositories{
   mavenCentral()
}
dependencies {
   compileOnly "org.projectlombok:lombok:${LOMBOK_VERSION}"
   annotationProcessor "org.projectlombok:lombok:${LOMBOK_VERSION}"
   api 'net.datafaker:datafaker:2.4.3'
   testImplementation 'org.junit.jupiter:junit-jupiter:6.0.0-RC1'
}

tasks.test{
   useJUnitPlatform()
}
